version: "3"

services:
  letsencrypt-dns:
    image: adferrand/letsencrypt-dns
    container_name: letsencrypt-dns
    restart: always
    volumes:
      - /etc/letsencrypt/domains.conf:/etc/letsencrypt/domains.conf
      - /etc/letsencrypt:/etc/letsencrypt
    env_file: .env
    deploy:
      mode: global
      update_config:
        delay: 5s
