version: 0.1
log:
  accesslog:
    disabled: true
  level: info
  formatter: text
#  hooks:
#    - type: mail
#      disabled: true
#      levels:
#        - panic
#      options:
#        smtp:
#          addr: mail.example.com:25
#          username: mailuser
#          password: password
#          insecure: true
#        from: registry@rezerbit.com
#        to:
#          - rezerbit@gmail.com
loglevel: info
#storage:
#  s3:
#    accesskey: 19449fd7e6ff
#    secretkey: 002f20dbfe13c1f816d3746a4aa23b062f0e18df94
#    region: us-east-1
#    bucket: registry-rezerbit
auth:
  htpasswd:
    realm: basic-realm
    path: /httpasswd_storage/.htpasswd
http:
  addr: registry:5000
#  prefix: /my/nested/registry/
  host: https://registry.rezerbit.com:5000
#  secret: asecretforlocaldevelopment
#  relativeurls: false
  tls:
    certificate: /etc/letsencrypt/live/rezerbit.com/fullchain.pem
    key: /etc/letsencrypt/live/rezerbit.com/privkey.pem
#  debug:
#    addr: localhost:5001
#  headers:
#    X-Content-Type-Options: [nosniff]
#  http2:
#    disabled: false
