version: '3'
services:
  registry:
    image: registry
    restart: always
    env_file: .env
    environment:
      TCP_PORTS: '5000'
      VIRTUAL_HOST: '*:5000, https://*:5000'
      FORCE_SSL: 'true'
      REGISTRY_STORAGE_DELETE_ENABLED: 'true'
    volumes:
      - /etc/nginx/httpasswd_storage/.htpasswd:/httpasswd_storage/.hthtpasswd

  registry-ui:
    image: konradkleine/docker-registry-frontend:v2
    restart: always
    environment:
      VIRTUAL_HOST: '*, https://*'
      ENV_DOCKER_REGISTRY_HOST: 'registry'
      ENV_DOCKER_REGISTRY_PORT: 5000
    links:
      - registry
    networks:
      - nginx-front

networks:
  nginx-front:
    external: true
