version: "3"

services:
  nginx:
    image: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/log/nginx:/var/log/nginx:rw
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/nginx/conf.d:/etc/nginx/conf.d:ro
      - /etc/nginx/httpasswd_storage:/etc/nginx/httpasswd_storage:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /usr/share/nginx/html:/usr/share/nginx/html
    logging:
      options:
        max-size: ${NGINX_FRONT_LOG_MAX_SIZE:-4m}
        max-file: ${NGINX_FRONT_LOG_MAX_FILE:-10}
    deploy:
      replicas: 1
      update_config:
        delay: 5s
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == manager]

# Do not forget to 'docker network create -d overlay nginx-front' before launch,
# and to add '--network nginx-front' to proxied containers.
networks:
  default:
    external:
      name: nginx-front
    driver: overlay
