version: '3'

services:
  agent:
    image: portainer/agent
    environment:
      # REQUIRED: Should be equal to the service name prefixed by "tasks." when
      # deployed inside an overlay network
      AGENT_CLUSTER_ADDR: tasks.agent
      AGENT_PORT: 9001
      # LOG_LEVEL: debug
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - agent_network
    deploy:
      mode: global

  portainer:
    image: portainer/portainer
    depends_on:
      - agent
    command: -H tcp://tasks.agent:9001 --templates $TEMPLATES_URL
    ports:
      - 9000
    volumes:
      - portainer_data:/data
    networks:
      - agent_network
      - nginx-front
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]

networks:
  agent_network:
    driver: overlay
  nginx-front:
    external: true

volumes:
  portainer_data:
