version: '3.2'

services:
  agent:
    image: portainer/agent
    environment:
      # REQUIRED: Should be equal to the service name prefixed by "tasks." when
      # deployed inside an overlay network
      AGENT_CLUSTER_ADDR: tasks.agent
      # LOG_LEVEL: debug
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    ports:
      - target: 9001
        published: 9001
        protocol: tcp
        mode: host
    networks:
      - default
      - portainer_agent
    deploy:
      mode: global
      update_config:
        delay: 5s
      restart_policy:
        condition: on-failure

  portainer:
    image: portainer/portainer
    depends_on:
      - agent
    command: -H tcp://tasks.portainer_agent:9001 --tlsskipverify
    ports:
      - 9000
    volumes:
      - portainer_data:/data
    networks:
      - default
      - portainer_agent
      - nginx-front
    deploy:
      mode: replicated
      replicas: 1
      update_config:
        delay: 5s
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: on-failure

networks:
  portainer_agent:
    driver: overlay
    attachable: true
  nginx-front:
    external: true

volumes:
  portainer_data:
