version: "3"

services:
  volumerize:
    image: blacklabelops/volumerize
    container_name: volumerize
    volumes:
      - cache:/volumerize-cache
      - virtsoil_db-data:/source/virtsoil_db-data:ro
      - virtsoil_wordpress-data:/source/virtsoil_wordpress-data:ro
    env_file: .env
    deploy:
      mode: global
      update_config:
        delay: 5s

volumes:
  cache:
  virtsoil_db-data:
    external: true
  virtsoil_db-data:
    external: true
