version: '3'

services:
  minio:
    image: minio/minio
    restart: always
    command: "gateway b2"
    env_file: .env
    environment:
      - MINIO_ACCESS_KEY
      - MINIO_SECRET_KEY
    volumes:
      - minio-data:/export
    networks:
      - nginx-front
    deploy:
      replicas: 1
      restart_policy:
        delay: 10s
      placement:
        constraints: [node.role == manager]
volumes:
  minio-data:

networks:
  nginx-front:
    external: true
